# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update db incrementally

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Los_Angeles
    - name: Google project credentials
      env:
        GOOGLE_SVC_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SVC_ACCOUNT_CREDENTIALS }}
      run: echo "${GOOGLE_SVC_ACCOUNT_CREDENTIALS}" > /tmp/.googleCredentials.json
    - run: npm ci; npm install -g ts-node json2csv
    - run: cd docker-db; npm ci  ; cd ..
    - run: which psql
    - name: download data
      env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/.googleCredentials.json
      run: cd docker-db; sh -vxe initdb.sh download_changes
    - name: updatedb data
      env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/.googleCredentials.json
          CONN: ${{secrets.CONN}}
      run: cd docker-db; sh -vxe initdb.sh update_db